### ISSUE TITLE
TypeError: FabricDeepSpeedZeroOptimizer is not an Optimizer

### ISSUE THREAD

**Issue by easonfzw** [Lightning-AI/pytorch-lightning#17584] opened 2023-05-06 08:09 UTC
### Bug description

In the scenario where fabric uses deepspeed stragety, lr_scheduler will make an error 
TypeError: FabricDeepSpeedZeroOptimizer is not an Optimizer

### What version are you seeing the problem on?

master

### How to reproduce the bug

```python
213 def load_lr_scheduler(optimizer, num_step):
214     args.overrode_max_train_steps = False
215     args.num_update_steps_per_epoch = math.ceil(num_step / args.gradient_accumulation_steps)
216     if args.max_train_steps is None:
217         args.max_train_steps = args.num_train_epochs * args.num_update_steps_per_epoch
218         args.overrode_max_train_steps = True
219 
220     lr_scheduler = get_scheduler(
221         name=args.lr_scheduler_type,
222         optimizer=optimizer,
223         num_warmup_steps=args.num_warmup_steps * args.gradient_accumulation_steps,
224         num_training_steps=args.max_train_steps * args.gradient_accumulation_steps,
225     )
226     return lr_scheduler
...

355 def main():
356 
357     # Get Dataset
358     raw_datasets = dataset_setup()
359 
360     # Get config
361     config = get_config()
362 
363     # Get Tokenizer
364     tokenizer = get_tokenizer()
365 
366 
367     # Dataset preprocessing with tokenizer
368     train_dataloader, eval_dataloader = dataset_preprocess(tokenizer, raw_datasets)
369 
370     fabric = Fabric(accelerator="cuda", devices=4, strategy="deepspeed_stage_2", precision="16-mixed")
371     fabric.launch()
372 
373     # Load Model
374     model = load_model(config, tokenizer)
375 
376     # Dataset preprocessing with tokenizer
377     #train_dataloader, eval_dataloader = dataset_preprocess(tokenizer, raw_datasets)
378 
379     # Load Optimizer
380     optimizer = load_optimizer(model)
381 
382 
383     # Initialize fabric
384     model, optimizer = fabric.setup(model, optimizer)
385 
386     # load lr_scheduler
387     lr_scheduler = load_lr_scheduler(optimizer, len(train_dataloader))
388 
389     train_dataloader, eval_dataloader = fabric.setup_dataloaders(train_dataloader, eval_dataloader)
390 
391     fabric.barrier()
392 
393     # Only show the progress bar once on each machine.
394     train(model, train_dataloader, eval_dataloader, optimizer, lr_scheduler, fabric)
```

### Error messages and logs

```
/home/llm/gpt2-train/run_fabric_train.py:387 in main                              │
│                                                                                                  │
│   384 │   model, optimizer = fabric.setup(model, optimizer)                                      │
│   385 │                                                                                          │
│   386 │   # load lr_scheduler                                                                    │
│ ❱ 387 │   lr_scheduler = load_lr_scheduler(optimizer, len(train_dataloader))                     │
│   388 │                                                                                          │
│   389 │   train_dataloader, eval_dataloader = fabric.setup_dataloaders(train_dataloader, eval_   │
│   390                                                                                            │
│                                                                                                  │
│ /home/llm/gpt2-train/run_fabric_train.py:220 in load_lr_scheduler                 │
│                                                                                                  │
│   217 │   │   args.max_train_steps = args.num_train_epochs * args.num_update_steps_per_epoch     │
│   218 │   │   args.overrode_max_train_steps = True                                               │
│   219 │                                                                                          │
│ ❱ 220 │   lr_scheduler = get_scheduler(                                                          │
│   221 │   │   name=args.lr_scheduler_type,                                                       │
│   222 │   │   optimizer=optimizer,                                                               │
│   223 │   │   num_warmup_steps=args.num_warmup_steps * args.gradient_accumulation_steps,         │
│                                                                                                  │
│ /home/.conda/envs/py310/lib/python3.10/site-packages/transformers/optimization.py:355   │
│ in get_scheduler                                                                                 │
│                                                                                                  │
│   352 │   if num_training_steps is None:                                                         │
│   353 │   │   raise ValueError(f"{name} requires `num_training_steps`, please provide that arg   │
│   354 │                                                                                          │
│ ❱ 355 │   return schedule_func(optimizer, num_warmup_steps=num_warmup_steps, num_training_step   │
│   356                                                                                            │
│   357                                                                                            │
│   358 class AdamW(Optimizer):                                                                    │
│                                                                                                  │
│ /home/.conda/envs/py310/lib/python3.10/site-packages/transformers/optimization.py:109   │
│ in get_linear_schedule_with_warmup                                                               │
│                                                                                                  │
│   106 │   │   num_warmup_steps=num_warmup_steps,                                                 │
│   107 │   │   num_training_steps=num_training_steps,                                             │
│   108 │   )                                                                                      │
│ ❱ 109 │   return LambdaLR(optimizer, lr_lambda, last_epoch)                                      │
│   110                                                                                            │
│   111                                                                                            │
│   112 def _get_cosine_schedule_with_warmup_lr_lambda(                                            │
│                                                                                                  │
│ /home/.conda/envs/py310/lib/python3.10/site-packages/torch/optim/lr_scheduler.py:221 in │
│ __init__                                                                                         │
│                                                                                                  │
│    218 │   │   │   │   raise ValueError("Expected {} lr_lambdas, but got {}".format(             │
│    219 │   │   │   │   │   len(optimizer.param_groups), len(lr_lambda)))                         │
│    220 │   │   │   self.lr_lambdas = list(lr_lambda)                                             │
│ ❱  221 │   │   super().__init__(optimizer, last_epoch, verbose)                                  │
│    222 │                                                                                         │
│    223 │   def state_dict(self):                                                                 │
│    224 │   │   """Returns the state of the scheduler as a :class:`dict`.                         │
│                                                                                                  │
│ /home/.conda/envs/py310/lib/python3.10/site-packages/torch/optim/lr_scheduler.py:32 in  │
│ __init__                                                                                         │
│                                                                                                  │
│     29 │   │                                                                                     │
│     30 │   │   # Attach optimizer                                                                │
│     31 │   │   if not isinstance(optimizer, Optimizer):                                          │
│ ❱   32 │   │   │   raise TypeError('{} is not an Optimizer'.format(                              │
│     33 │   │   │   │   type(optimizer).__name__))                                                │
│     34 │   │   self.optimizer = optimizer                                                        │
│     35                                                                                           │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
TypeError: FabricDeepSpeedZeroOptimizer is not an Optimizer
```

### Environment

<details>
  <summary>Current environment</summary>

* CUDA:
	- GPU:
		- NVIDIA A100-PCIE-40GB
	- available:         True
	- version:           11.7
* Lightning:
	- lightning:         2.0.2
	- lightning-cloud:   0.5.34
	- lightning-utilities: 0.8.0
	- pytorch-lightning: 2.0.2
	- torch:             2.0.0
	- torchmetrics:      0.11.4
* Packages:
	- accelerate:        0.18.0
	- aiohttp:           3.8.4
	- aiosignal:         1.3.1
	- anyio:             3.6.2
	- arrow:             1.2.3
	- asttokens:         2.2.1
	- async-timeout:     4.0.2
	- attrs:             22.2.0
	- backcall:          0.2.0
	- beautifulsoup4:    4.12.2
	- blessed:           1.20.0
	- certifi:           2022.12.7
	- charset-normalizer: 3.1.0
	- click:             8.1.3
	- cmake:             3.26.3
	- contourpy:         1.0.7
	- croniter:          1.3.14
	- cycler:            0.11.0
	- datasets:          2.11.0
	- dateutils:         0.6.12
	- decorator:         5.1.1
	- deepdiff:          6.3.0
	- deepspeed:         0.9.2
	- dill:              0.3.6
	- evaluate:          0.4.0
	- executing:         1.2.0
	- fastapi:           0.88.0
	- filelock:          3.10.7
	- fonttools:         4.39.3
	- frozenlist:        1.3.3
	- fsspec:            2023.3.0
	- h11:               0.14.0
	- hjson:             3.1.0
	- huggingface-hub:   0.13.3
	- idna:              3.4
	- inquirer:          3.1.3
	- ipython:           8.13.2
	- itsdangerous:      2.1.2
	- jedi:              0.18.2
	- jinja2:            3.1.2
	- joblib:            1.2.0
	- kiwisolver:        1.4.4
	- lightning:         2.0.2
	- lightning-cloud:   0.5.34
	- lightning-utilities: 0.8.0
	- lit:               16.0.2
	- markdown-it-py:    2.2.0
	- markupsafe:        2.1.2
	- matplotlib:        3.7.1
	- matplotlib-inline: 0.1.6
	- mdurl:             0.1.2
	- mpmath:            1.3.0
	- multidict:         6.0.4
	- multiprocess:      0.70.14
	- networkx:          3.1
	- ninja:             1.11.1
	- numpy:             1.24.2
	- nvidia-cublas-cu11: 11.10.3.66
	- nvidia-cuda-cupti-cu11: 11.7.101
	- nvidia-cuda-nvrtc-cu11: 11.7.99
	- nvidia-cuda-runtime-cu11: 11.7.99
	- nvidia-cudnn-cu11: 8.5.0.96
	- nvidia-cufft-cu11: 10.9.0.58
	- nvidia-curand-cu11: 10.2.10.91
	- nvidia-cusolver-cu11: 11.4.0.1
	- nvidia-cusparse-cu11: 11.7.4.91
	- nvidia-nccl-cu11:  2.14.3
	- nvidia-nvtx-cu11:  11.7.91
	- ordered-set:       4.1.0
	- packaging:         23.0
	- pandas:            1.5.3
	- parso:             0.8.3
	- pexpect:           4.8.0
	- pickleshare:       0.7.5
	- pillow:            9.5.0
	- pip:               23.0.1
	- prompt-toolkit:    3.0.38
	- protobuf:          4.22.3
	- psutil:            5.9.5
	- ptyprocess:        0.7.0
	- pure-eval:         0.2.2
	- py-cpuinfo:        9.0.0
	- pyarrow:           11.0.0
	- pydantic:          1.10.7
	- pygments:          2.15.1
	- pyjwt:             2.6.0
	- pyparsing:         3.0.9
	- python-dateutil:   2.8.2
	- python-editor:     1.0.4
	- python-multipart:  0.0.6
	- pytorch-lightning: 2.0.2
	- pytz:              2023.3
	- pyyaml:            6.0
	- readchar:          4.0.5
	- regex:             2023.5.4
	- requests:          2.28.2
	- responses:         0.18.0
	- rich:              13.3.5
	- scikit-learn:      1.2.2
	- scipy:             1.10.1
	- sentencepiece:     0.1.99
	- setuptools:        65.6.3
	- six:               1.16.0
	- sniffio:           1.3.0
	- soupsieve:         2.4.1
	- stack-data:        0.6.2
	- starlette:         0.22.0
	- starsessions:      1.3.0
	- sympy:             1.11.1
	- threadpoolctl:     3.1.0
	- tokenizers:        0.13.3
	- torch:             2.0.0
	- torchmetrics:      0.11.4
	- tqdm:              4.65.0
	- traitlets:         5.9.0
	- transformers:      4.28.1
	- triton:            2.0.0
	- typing-extensions: 4.5.0
	- urllib3:           1.26.15
	- uvicorn:           0.22.0
	- watermark:         2.3.1
	- wcwidth:           0.2.6
	- websocket-client:  1.5.1
	- websockets:        11.0.2
	- wheel:             0.38.4
	- xxhash:            3.2.0
	- yarl:              1.8.2
* System:
	- OS:                Linux
	- architecture:
		- 64bit
		- ELF
	- processor:         x86_64
	- python:            3.10.9
	- release:           5.4.0-148-generic

</details>

cc @awaelchli @carmocca @justusschock

**Comment by awaelchli** [comment] 2023-05-07 01:00
This is because the DeepSpeedOptimizer from the deepspeed library itself is not of type `torch.optim.Optimizer` either. And so, when Fabric warps it, then naturally the instance check fails with that wrapper class too. See here in deepspeed, their optimizers just inherit from this class:

https://github.com/microsoft/DeepSpeed/blob/4e886f0568832d292183926bcc1a9105def25f2c/deepspeed/runtime/__init__.py#L11

For optimizers that are subclasses of `torch.optim.Optimizer`, our wrapper will pass the instance check. For example, here we test this:

https://github.com/Lightning-AI/lightning/blob/a36af3f9f855a4735fdc97c5e08bebb8a7467bf3/tests/tests_fabric/test_wrappers.py#L293-L299

@easonfzw Honestly I'm not sure what Lightning can do here. Suggestions welcome.

**Comment by awaelchli** [comment] 2023-05-07 01:04
I suggest that you load the lr_scheduler before calling `fabric.setup()`. Would that work?

**Comment by easonfzw** [comment] 2023-05-07 14:20
> I suggest that you load the lr_scheduler before calling `fabric.setup()`. Would that work?

Thanks for your reply, I load the lr_scheduler before calling fabric.setup() which produces another error : 
AttributeError: 'LambdaLR' object has no attribute 'backward'

The detailed error message is as follows:
`│   282 │   │   │   if args.with_tracking:                                                         │
│   283 │   │   │   │   total_loss += loss.detach().float()                                        │
│   284 │   │   │   #accelerator.backward(loss)                                                    │
│ ❱ 285 │   │   │   fabric.backward(loss)                                                          │
│   286 │   │   │   optimizer.step()                                                               │
│   287 │   │   │   lr_scheduler.step()                                                            │
│   288 │   │   │   optimizer.zero_grad()                                                          │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
AttributeError: 'LambdaLR' object has no attribute 'backward'
`

**Comment by jk4011** [comment] 2023-05-14 13:49
> I suggest that you load the lr_scheduler before calling `fabric.setup()`. Would that work?

Thank you so much.

**Comment by easonfzw** [comment] 2023-05-14 13:51
> > I suggest that you load the lr_scheduler before calling `fabric.setup()`. Would that work?
> 
> Thank you so much.

Can you run the code normally with lr_scheduler?

**Comment by jk4011** [comment] 2023-05-23 02:21
@easonfzw I had only an error below you first mentioned.
```TypeError: FabricDeepSpeedZeroOptimizer is not an Optimizer```

**Comment by jk4011** [comment] 2023-05-23 02:34
@easonfzw By the way, how can I use the multiple line error message like yours?
```
/home/llm/gpt2-train/run_fabric_train.py:387 in main                              │
│                                                                                                  │
│   384 │   model, optimizer = fabric.setup(model, optimizer)                                      │
│   385 │                                                                                          │
│   386 │   # load lr_scheduler                                                                    │
│ ❱ 387 │   lr_scheduler = load_lr_scheduler(optimizer, len(train_dataloader))                     │
│   388 │                                                                                          │
│   389 │   train_dataloader, eval_dataloader = fabric.setup_dataloaders(train_dataloader, eval_   │
│   390                                                                                            │
│                                                                                                  │
```

**Comment by easonfzw** [comment] 2023-05-23 02:49
> By the way, how can I use the multiple line error message like yours?

This is automatically printed out after the error is reported, I have not made any other settings

Other than that, can you please check that your code is the same way I use it in the training phase? I am very confused about this error, AttributeError: 'LambdaLR' object has no attribute 'backward'"

**Comment by jk4011** [comment] 2023-05-23 03:01
@easonfzw
> can you please check that your code is the same way I use it in the training phase?

Since my code is quite noisy, it might take amount of time to refactor to your format. Additionally, I am uncertain if my code will encounter the same error. 

Would it be possible for you to provide a minimal code example that reproduces the error? Then I can check yours.

**Comment by jk4011** [comment] 2023-05-23 03:05
> Are you also using deepspeed? 

I'm also using deepspeed stage 2 strategy.

**Comment by easonfzw** [comment] 2023-05-23 03:07
> > By the way, how can I use the multiple line error message like yours?
> 
> This is automatically printed out after the error is reported, I have not made any other settings
> 
> Other than that, can you please check that your code is the same way I use it in the training phase? I am very confused about this error, AttributeError: 'LambdaLR' object has no attribute 'backward'"



> > Are you also using deepspeed?
> 
> I'm also using deepspeed stage 2 strategy.

That's great, I'll post the code as soon as I prepare it, thank you very much!

**Comment by awaelchli** [comment] 2024-02-16 13:20
Closing this as https://github.com/Lightning-AI/pytorch-lightning/issues/17584#issuecomment-1537258527 seems to be the only solution. Anything set up with Fabric requires PyTorch optimizers. If someone still has issues with this, please also open a ticket on the DeepSpeed repo about the `DeepSpeedZeroOptimizer` not being a Optimizer subclass.

**Closed by awaelchli** 2024-02-16 13:20 UTC
Labels: bug, 3rd party, strategy: deepspeed, fabric, ver: 2.1.x

**Comment by carmocca** [comment] 2024-02-16 15:34
I once added support for "Optimizables" as optimizers to the Trainer: https://github.com/Lightning-AI/pytorch-lightning/pull/16189

Couldn't Fabric do the same? This requires that the deepspeed optimizer follows the same methods and API, even if it doesn't subclass the torch optimizer

**Comment by awaelchli** [comment] 2024-02-16 15:38
@carmocca The error happens in `lr_scheduler = load_lr_scheduler(optimizer, len(train_dataloader))` which is in user code. After the optimizer is set up by the strategy, it is what it is. In case of DeepSpeed, it is just their special class.
