### ISSUE TITLE
Unable to train on TPU v4-8: Failed to get global TPU topology.

### ISSUE THREAD

**Issue by fabienGenhealth** [Lightning-AI/pytorch-lightning#18932] opened 2023-11-03 10:07 UTC
### Bug description

A training script I refactored to train on TPU, which trains successfully on TPU v3-8 VM, fails when started with a v4-8 TPU VM. 

### What version are you seeing the problem on?

v2.1

### How to reproduce the bug

```python
Don't have a minimal reproducible example at this time. However, Fabric is initialized as follows:
    fabric = Fabric(
        accelerator="tpu",
        precision="bf16-true",
        devices='auto'
    )
```

### Error messages and logs

```
The stack trace is:

(task, pid=22934) concurrent.futures.process._RemoteTraceback: 
(task, pid=22934) """
(task, pid=22934) Traceback (most recent call last):
(task, pid=22934)   File "/home/gcpuser/miniconda3/envs/py310/lib/python3.10/concurrent/futures/process.py", line 246, in _process_worker
(task, pid=22934)     r = call_item.fn(*call_item.args, **call_item.kwargs)
(task, pid=22934)   File "/home/gcpuser/miniconda3/envs/py310/lib/python3.10/concurrent/futures/process.py", line 205, in _process_chunk
(task, pid=22934)     return [fn(*args) for args in chunk]
(task, pid=22934)   File "/home/gcpuser/miniconda3/envs/py310/lib/python3.10/concurrent/futures/process.py", line 205, in <listcomp>
(task, pid=22934)     return [fn(*args) for args in chunk]
(task, pid=22934)   File "/home/gcpuser/miniconda3/envs/py310/lib/python3.10/site-packages/torch_xla/runtime.py", line 82, in wrapper
(task, pid=22934)     return fn(*args, **kwargs)
(task, pid=22934)   File "/home/gcpuser/miniconda3/envs/py310/lib/python3.10/site-packages/torch_xla/_internal/pjrt.py", line 56, in _run_thread_per_device
(task, pid=22934)     initializer_fn(local_rank, local_world_size)
(task, pid=22934)   File "/home/gcpuser/miniconda3/envs/py310/lib/python3.10/site-packages/torch_xla/runtime.py", line 82, in wrapper
(task, pid=22934)     return fn(*args, **kwargs)
(task, pid=22934)   File "/home/gcpuser/miniconda3/envs/py310/lib/python3.10/site-packages/torch_xla/_internal/pjrt.py", line 115, in initialize_multiprocess
(task, pid=22934)     devices = xm.get_xla_supported_devices()
(task, pid=22934)   File "/home/gcpuser/miniconda3/envs/py310/lib/python3.10/site-packages/torch_xla/core/xla_model.py", line 91, in get_xla_supported_devices
(task, pid=22934)     xla_devices = _DEVICES.value
(task, pid=22934)   File "/home/gcpuser/miniconda3/envs/py310/lib/python3.10/site-packages/torch_xla/utils/utils.py", line 29, in value
(task, pid=22934)     self._value = self._gen_fn()
(task, pid=22934)   File "/home/gcpuser/miniconda3/envs/py310/lib/python3.10/site-packages/torch_xla/core/xla_model.py", line 19, in <lambda>
(task, pid=22934)     _DEVICES = xu.LazyProperty(lambda: torch_xla._XLAC._xla_get_devices())
(task, pid=22934) RuntimeError: Bad StatusOr access: INTERNAL: Failed to get global TPU topology.
```

### Environment

<details>
  <summary>Current environment</summary>

* CUDA:
	- GPU:               None
	- available:         False
	- version:           12.1
* Lightning:
	- lightning:         2.1.0
	- lightning-utilities: 0.9.0
	- pytorch-beam-search: 1.2.2
	- pytorch-lightning: 2.1.0
	- torch:             2.1.0
	- torch-xla:         2.1.0
	- torchmetrics:      1.2.0
	- torchscale:        0.3.0b0
	- torchtyping:       0.1.4
	- torchvision:       0.16.0
* Packages:
	- absl-py:           2.0.0
	- accelerate:        0.23.0
	- aiohttp:           3.8.6
	- aiosignal:         1.3.1
	- appdirs:           1.4.4
	- async-timeout:     4.0.3
	- attrs:             23.1.0
	- braceexpand:       0.1.7
	- cachetools:        5.3.2
	- certifi:           2023.7.22
	- cffi:              1.16.0
	- charset-normalizer: 3.3.2
	- click:             8.1.7
	- cloud-tpu-client:  0.10
	- cryptography:      41.0.5
	- docker-pycreds:    0.4.0
	- einops:            0.6.1
	- fairscale:         0.4.0
	- filelock:          3.13.1
	- frozenlist:        1.4.0
	- fsspec:            2023.10.0
	- gitdb:             4.0.11
	- gitpython:         3.1.40
	- google-api-core:   1.34.0
	- google-api-python-client: 1.8.0
	- google-auth:       2.23.4
	- google-auth-httplib2: 0.1.1
	- googleapis-common-protos: 1.61.0
	- greenfield-lmm:    0.1.1
	- httplib2:          0.22.0
	- huggingface-hub:   0.18.0
	- idna:              3.4
	- importlib-metadata: 6.8.0
	- jaraco.classes:    3.3.0
	- jeepney:           0.8.0
	- jinja2:            3.1.2
	- joblib:            1.3.2
	- keyring:           24.2.0
	- keyrings.google-artifactregistry-auth: 1.1.2
	- libtpu-nightly:    0.1.dev20230825+default
	- lightning:         2.1.0
	- lightning-utilities: 0.9.0
	- markupsafe:        2.1.3
	- more-itertools:    10.1.0
	- mpmath:            1.3.0
	- multidict:         6.0.4
	- networkx:          3.2.1
	- ninja:             1.11.1.1
	- nltk:              3.8.1
	- numpy:             1.26.1
	- nvidia-cublas-cu12: 12.1.3.1
	- nvidia-cuda-cupti-cu12: 12.1.105
	- nvidia-cuda-nvrtc-cu12: 12.1.105
	- nvidia-cuda-runtime-cu12: 12.1.105
	- nvidia-cudnn-cu12: 8.9.2.26
	- nvidia-cufft-cu12: 11.0.2.54
	- nvidia-curand-cu12: 10.3.2.106
	- nvidia-cusolver-cu12: 11.4.5.107
	- nvidia-cusparse-cu12: 12.1.0.106
	- nvidia-nccl-cu12:  2.18.1
	- nvidia-nvjitlink-cu12: 12.3.52
	- nvidia-nvtx-cu12:  12.1.105
	- oauth2client:      4.1.3
	- packaging:         23.2
	- pandas:            2.1.2
	- pathtools:         0.1.2
	- patsy:             0.5.3
	- pillow:            10.1.0
	- pip:               23.3
	- plotly:            5.18.0
	- pluggy:            1.3.0
	- polars:            0.19.12
	- protobuf:          3.20.3
	- psutil:            5.9.6
	- pyarrow:           13.0.0
	- pyasn1:            0.5.0
	- pyasn1-modules:    0.3.0
	- pycparser:         2.21
	- pyparsing:         3.1.1
	- python-dateutil:   2.8.2
	- pytorch-beam-search: 1.2.2
	- pytorch-lightning: 2.1.0
	- pytz:              2023.3.post1
	- pyyaml:            6.0.1
	- regex:             2023.10.3
	- requests:          2.31.0
	- rsa:               4.9
	- safetensors:       0.3.3
	- scipy:             1.11.3
	- secretstorage:     3.3.3
	- sentry-sdk:        1.34.0
	- setproctitle:      1.3.3
	- setuptools:        68.0.0
	- six:               1.16.0
	- smmap:             5.0.1
	- statsmodels:       0.14.0
	- sympy:             1.12
	- tenacity:          8.2.3
	- timm:              0.6.13
	- torch:             2.1.0
	- torch-xla:         2.1.0
	- torchmetrics:      1.2.0
	- torchscale:        0.3.0b0
	- torchtyping:       0.1.4
	- torchvision:       0.16.0
	- tqdm:              4.66.1
	- triton:            2.1.0
	- typeguard:         2.13.3
	- typing-extensions: 4.8.0
	- tzdata:            2023.3
	- ujson:             5.8.0
	- uritemplate:       3.0.1
	- urllib3:           2.0.7
	- wandb:             0.15.12
	- webdataset:        0.2.73
	- wheel:             0.41.2
	- yarl:              1.9.2
	- zipp:              3.17.0
* System:
	- OS:                Linux
	- architecture:
		- 64bit
		- ELF
	- processor:         x86_64
	- python:            3.10.13
	- release:           5.13.0-1027-gcp
	- version:           #32~20.04.1-Ubuntu SMP Thu May 26 10:53:08 UTC 2022

</details>

cc @carmocca @JackCaoG @Liyang90 @gkroiz

**Comment by carmocca** [comment] 2023-11-09 12:40
I haven't experienced this error before. Are you able to reproduce it every time? Perhaps somebody from the XLA team knows what could be the cause

**Comment by fabienGenhealth** [comment] 2023-11-09 13:39
Yes, it's been reproducible each time I tried to get a v4-8 (or v4-32) instance.

**Comment by fabienGenhealth** [comment] 2023-11-09 13:40
Are you able to run any model with a v4-8 TPU VM?

**Comment by jchauhan** [comment] 2024-02-26 17:38
@fabienGenhealth Did you get it solved? I am facing the same error

**Comment by carmocca** [comment] 2024-02-26 18:33
I don't have access to these machines right now to try, but there were recent reports about issues in Colab too: https://github.com/Lightning-AI/pytorch-lightning/issues/19274

If likely that the problem is in your installation or in XLA directly

**Comment by gkroiz** [comment] 2024-02-26 19:38
I will take a look at this, will test Lit-GPT on v4 to see if anything comes up

**Comment by gkroiz** [comment] 2024-02-26 23:56
I was able to test Lit-GPT on v4. Here is how to reproduce on v4-8 using python 3.10:
```
pip install torch~=2.1.0 torch_xla[tpu]~=2.1.0 -f https://storage.googleapis.com/libtpu-releases/index.html # based on pypi recommendation
git clone https://github.com/Lightning-AI/lit-gpt.git
cd lit-gpt && git checkout 39a00bcf4d317b6be998a60584caa446e25f32ce
pip install -r requirements-all.txt 
python scripts/download.py --repo_id EleutherAI/pythia-70m
python scripts/convert_hf_checkpoint.py --checkpoint_dir checkpoints/EleutherAI/pythia-70m
python3 scripts/prepare_alpaca.py --checkpoint_dir checkpoints/EleutherAI/pythia-70m
python3 xla/finetune/adapter.py --checkpoint_dir checkpoints/EleutherAI/pythia-70m/ --precision bf16-true
```

@fabienGenhealth @jchauhan How are you installing pytorch and pytorch xla? Maybe these are being installed incorrectly for TPUs?

**Comment by jchauhan** [comment] 2024-02-27 06:24
I got it fixed by following instructions. I was using older version v2.alpha as version while creating instance. Issue resolved. Thanks

**Closed** 2024-02-27 12:31 UTC
Labels: bug, accelerator: tpu, 3rd party, ver: 2.1.x

**Comment by fabienGenhealth** [comment] 2024-02-27 14:21
I moved on from trying to use TPUs, this error did not make it practical at the time.
