### ISSUE TITLE
Root module wrapped when using custom FSDP strategy

### ISSUE THREAD

**Issue by asuglia-alana** [Lightning-AI/pytorch-lightning#18944] opened 2023-11-04 10:00 UTC
### Bug description

This is an issue that was supposed to be closed in https://github.com/Lightning-AI/lightning/pull/18054 but unfortunately I'm able to reproduce it when using the auto-wrapping policy from `FSDPStrategy`.  The problem doesn't happen when using the old code with the manual `wrap`.  Cc'ing @carmocca 

### What version are you seeing the problem on?

v2.1

### How to reproduce the bug

```python
import torch
import lightning as L
from lightning.fabric.strategies.fsdp import FSDPStrategy
from torch.distributed.fsdp.fully_sharded_data_parallel import FullyShardedDataParallel

def setup():
  strategy = FSDPStrategy(
            auto_wrap_policy={torch.nn.Linear},
            activation_checkpointing_policy={torch.nn.Linear},
            state_dict_type="full",
            limit_all_gathers=True,
            cpu_offload=False,
        )
  fabric = L.Fabric(devices=2, accelerator="cuda", strategy=strategy)
  fabric.launch(main)

def main(fabric: L.Fabric):
  fabric.print("LAUNCH")

  with fabric.init_module(empty_init=True):
      l1 = torch.nn.Linear(5, 2)
      l2 = torch.nn.Linear(2, 1)
      model = torch.nn.Sequential(l1, torch.nn.ReLU(), l2)

  fabric.print(model)
  assert not isinstance(model, FullyShardedDataParallel)

  """
  Sequential(
    (0): FullyShardedDataParallel(
      (_fsdp_wrapped_module): Linear(in_features=1, out_features=1, bias=True)
    )
    (1): ReLU()
    (2): FullyShardedDataParallel(
      (_fsdp_wrapped_module): Linear(in_features=1, out_features=1, bias=True)
    )
  )
  """

  # FAILS: assumes the root is FSDP wrapped
  # fabric.save("/tmp/foo", {"model": model})

  model = fabric.setup_module(model)

  fabric.print(model)
  # AssertionError
  assert not isinstance(model._forward_module, FullyShardedDataParallel)

  """
  _FabricModule(
    (_forward_module): FullyShardedDataParallel(
      (_fsdp_wrapped_module): Sequential(
        (0): FullyShardedDataParallel(
          (_fsdp_wrapped_module): Linear(in_features=1, out_features=1, bias=True)
        )
        (1): ReLU()
        (2): FullyShardedDataParallel(
          (_fsdp_wrapped_module): Linear(in_features=1, out_features=1, bias=True)
        )
      )
    )
    (_original_module): Sequential(
      (0): FullyShardedDataParallel(
        (_fsdp_wrapped_module): Linear(in_features=1, out_features=1, bias=True)
      )
      (1): ReLU()
      (2): FullyShardedDataParallel(
        (_fsdp_wrapped_module): Linear(in_features=1, out_features=1, bias=True)
      )
    )
  )
  """

  with fabric.no_backward_sync(model, enabled=False):
    x = torch.ones((5, 5))

    y = model(x)

if __name__ == "__main__":
  setup()
```

### Error messages and logs

```
  File "/users/as2180/workspace/test_lightning.py", line 48, in main
    assert not isinstance(model._forward_module, FullyShardedDataParallel)
AssertionError
```

### Environment

<details>
  <summary>Current environment</summary>

* CUDA:
        - GPU:
                - A40
                - A40
        - available:         True
        - version:           11.7
* Lightning:
        - lightning:         2.1.0
        - lightning-utilities: 0.9.0
        - pytorch-lightning: 2.1.0
        - torch:             2.0.1
        - torchaudio:        2.0.2
        - torchmetrics:      1.2.0
        - torchvision:       0.15.2
* Packages:
        - aiohttp:           3.8.6
        - aiosignal:         1.3.1
        - asttokens:         2.2.1
        - async-timeout:     4.0.3
        - attrs:             23.1.0
        - backcall:          0.2.0
        - boltons:           23.0.0
        - brotlipy:          0.7.0
        - certifi:           2023.5.7
        - cffi:              1.15.1
        - charset-normalizer: 2.0.4
        - conda:             23.5.0
        - conda-content-trust: 0.1.3
        - conda-package-handling: 2.0.2
        - conda-package-streaming: 0.7.0
        - cryptography:      39.0.1
        - decorator:         5.1.1
        - executing:         1.2.0
        - filelock:          3.12.2
        - frozenlist:        1.4.0
        - fsspec:            2023.6.0
        - gmpy2:             2.1.2
        - huggingface-hub:   0.15.1
        - idna:              3.4
        - ipython:           8.14.0
        - jedi:              0.18.2
        - jinja2:            3.1.2
        - jsonpatch:         1.32
        - jsonpointer:       2.1
        - lightning:         2.1.0
        - lightning-utilities: 0.9.0
        - markupsafe:        2.1.1
        - matplotlib-inline: 0.1.6
        - mkl-fft:           1.3.6
        - mkl-random:        1.2.2
        - mkl-service:       2.4.0
        - mpmath:            1.2.1
        - multidict:         6.0.4
        - networkx:          2.8.4
        - numpy:             1.25.0
        - packaging:         23.0
        - parso:             0.8.3
        - pexpect:           4.8.0
        - pickleshare:       0.7.5
        - pillow:            9.4.0
        - pip:               23.0.1
        - pluggy:            1.0.0
        - prompt-toolkit:    3.0.38
        - ptyprocess:        0.7.0
        - pure-eval:         0.2.2
        - pycosat:           0.6.4
        - pycparser:         2.21
        - pygments:          2.15.1
        - pyopenssl:         23.0.0
        - pysocks:           1.7.1
        - pytorch-lightning: 2.1.0
        - pyyaml:            6.0
        - regex:             2023.6.3
        - requests:          2.28.1
        - ruamel.yaml:       0.17.21
        - ruamel.yaml.clib:  0.2.6
        - safetensors:       0.3.1
        - setuptools:        65.6.3
        - six:               1.16.0
        - stack-data:        0.6.2
        - sympy:             1.11.1
        - tokenizers:        0.13.3
        - toolz:             0.12.0
        - torch:             2.0.1
        - torchaudio:        2.0.2
        - torchmetrics:      1.2.0
        - torchvision:       0.15.2
        - tqdm:              4.65.0
        - traitlets:         5.9.0
        - transformers:      4.31.0.dev0
        - triton:            2.0.0
        - typing-extensions: 4.6.3
        - urllib3:           1.26.15
        - wcwidth:           0.2.6
        - wheel:             0.38.4
        - yarl:              1.9.2
        - zstandard:         0.19.0
* System:
        - OS:                Linux
        - architecture:
                - 64bit
                - ELF
        - processor:         x86_64
        - python:            3.10.10
        - release:           3.10.0-1160.80.1.el7.x86_64
        - version:           #1 SMP Tue Nov 8 15:48:59 UTC 2022

</details>

cc @awaelchli @carmocca

**Comment by awaelchli** [comment] 2023-11-04 12:12
@asuglia-alana When auto-wrapping, this is expected. There will always be a root FSDP module. 
See https://pytorch.org/docs/stable/fsdp.html and https://pytorch.org/tutorials/intermediate/FSDP_tutorial.html

**Comment by asuglia-alana** [comment] 2023-11-04 15:13
Hey @awaelchli, many thanks for the prompt response. Let me clarify my current situation: for a custom model that I'm trying to train using FSDP (for which I cannot disclose code), I am getting the following error when using the auto wrap functionality that you also have in lit-gpt: 

```
 ❱ 355 │   │   logits = model(train_batch)                                    │
│   356 │   │   fabric.print("logits {logits}")                                │
│   357 │   │   loss = compute_loss(loss_fn, logits, train_batch)              │
│   358 │   │   fabric.print("loss {loss}")                                    │
│                                                                              │
│ /usr/lib/python3/dist-packages/torch/nn/modules/module.py:1518 in            │
│ _wrapped_call_impl                                                           │
│                                                                              │
│   1515 │   │   if self._compiled_call_impl is not None:                      │
│   1516 │   │   │   return self._compiled_call_impl(*args, **kwargs)  # type: │
│   1517 │   │   else:                                                         │
│ ❱ 1518 │   │   │   return self._call_impl(*args, **kwargs)                   │
│   1519 │                                                                     │
│   1520 │   def _call_impl(self, *args, **kwargs):                            │
│   1521 │   │   forward_call = (self._slow_forward if torch._C._get_tracing_s │
│                                                                              │
│ /usr/lib/python3/dist-packages/torch/nn/modules/module.py:1527 in _call_impl │
│                                                                              │
│   1524 │   │   if not (self._backward_hooks or self._backward_pre_hooks or s │
│   1525 │   │   │   │   or _global_backward_pre_hooks or _global_backward_hoo │
│   1526 │   │   │   │   or _global_forward_hooks or _global_forward_pre_hooks │
│ ❱ 1527 │   │   │   return forward_call(*args, **kwargs)                      │
│   1528 │   │                                                                 │
│   1529 │   │   try:                                                          │
│   1530 │   │   │   result = None                                             │
│                                                                              │
│ /usr/lib/python3/dist-packages/lightning/fabric/wrappers.py:121 in forward   │
│                                                                              │
│   118 │   │   args, kwargs = self._precision.convert_input((args, kwargs))   │
│   119 │   │                                                                  │
│   120 │   │   with self._precision.forward_context():                        │
│ ❱ 121 │   │   │   output = self._forward_module(*args, **kwargs)             │
│   122 │   │                                                                  │
│   123 │   │   output = self._precision.convert_output(output)                │
│   124 │   │   return output                                                  │
│                                                                              │
│ /usr/lib/python3/dist-packages/torch/nn/modules/module.py:1518 in            │
│ _wrapped_call_impl                                                           │
│                                                                              │
│   1515 │   │   if self._compiled_call_impl is not None:                      │
│   1516 │   │   │   return self._compiled_call_impl(*args, **kwargs)  # type: │
│   1517 │   │   else:                                                         │
│ ❱ 1518 │   │   │   return self._call_impl(*args, **kwargs)                   │
│   1519 │                                                                     │
│   1520 │   def _call_impl(self, *args, **kwargs):                            │
│   1521 │   │   forward_call = (self._slow_forward if torch._C._get_tracing_s │
│                                                                              │
│ /usr/lib/python3/dist-packages/torch/nn/modules/module.py:1527 in _call_impl │
│                                                                              │
│   1524 │   │   if not (self._backward_hooks or self._backward_pre_hooks or s │
│   1525 │   │   │   │   or _global_backward_pre_hooks or _global_backward_hoo │
│   1526 │   │   │   │   or _global_forward_hooks or _global_forward_pre_hooks │
│ ❱ 1527 │   │   │   return forward_call(*args, **kwargs)                      │
│   1528 │   │                                                                 │
│   1529 │   │   try:                                                          │
│   1530 │   │   │   result = None                                             │
│                                                                              │
│ /usr/lib/python3/dist-packages/torch/distributed/fsdp/fully_sharded_data_par │
│ allel.py:823 in forward                                                      │
│                                                                              │
│    820 │   │   with torch.autograd.profiler.record_function(                 │
│    821 │   │   │   "FullyShardedDataParallel.forward"                        │
│    822 │   │   ):                                                            │
│ ❱  823 │   │   │   args, kwargs = _root_pre_forward(self, self, args, kwargs │
│    824 │   │   │   unused = None                                             │
│    825 │   │   │   args, kwargs = _pre_forward(                              │
│    826 │   │   │   │   self,                                                 │
│                                                                              │
│ /usr/lib/python3/dist-packages/torch/distributed/fsdp/_runtime_utils.py:557  │
│ in _root_pre_forward                                                         │
│                                                                              │
│    554 │   │   │   may not be the root. If not, then this method does not do │
│    555 │   """                                                               │
│    556 │   with torch.profiler.record_function("FullyShardedDataParallel._ro │
│ ❱  557 │   │   _lazy_init(state, module)                                     │
│    558 │   │   _p_assert(state._is_root is not None, "Expects a root FSDP to │
│    559 │   │   if not state._is_root:                                        │
│    560 │   │   │   # Always cast forward inputs in the root of this local FS │
│                                                                              │
│ /usr/lib/python3/dist-packages/torch/distributed/fsdp/_runtime_utils.py:173  │
│ in _lazy_init                                                                │
│                                                                              │
│    170 │   buffers, buffer_dtypes = _get_buffers_and_dtypes_for_computation( │
│    171 │   _cast_buffers_to_dtype_and_device(buffers, buffer_dtypes, state.c │
│    172 │   state._exec_order_data.init(state, root_module, state.process_gro │
│ ❱  173 │   _share_state_and_init_handle_attrs(state, root_module)            │
│    174 │   return state                                                      │
│    175                                                                       │
│    176                                                                       │
│                                                                              │
│ /usr/lib/python3/dist-packages/torch/distributed/fsdp/_runtime_utils.py:260  │
│ in _share_state_and_init_handle_attrs                                        │
│                                                                              │
│    257 │   │   # Relax the assert for non-root FSDP instances in case the ne │
│    258 │   │   # initialized module is wrapped again in FSDP later (e.g. aft │
│    259 │   │   # training to run inference)                                  │
│ ❱  260 │   │   _p_assert(                                                    │
│    261 │   │   │   fsdp_state._is_root is None or not fsdp_state._is_root,   │
│    262 │   │   │   "Non-root FSDP instance's `_is_root` should not have been │
│    263 │   │   │   "set yet or should have been set to `False`",             │
│                                                                              │
│ /usr/lib/python3/dist-packages/torch/distributed/utils.py:147 in _p_assert   │
│                                                                              │
│   144 │   │   print(s)                                                       │
│   145 │   │   traceback.print_stack()                                        │
│   146 │   │   if raise_assertion_error:                                      │
│ ❱ 147 │   │   │   raise AssertionError(s)                                    │
│   148                                                                        │
│   149                                                                        │
│   150 def _alloc_storage(tensor: torch.Tensor, size: torch.Size) -> bool:    │
╰──────────────────────────────────────────────────────────────────────────────╯
AssertionError: Non-root FSDP instance's `_is_root` should not have been set yet
or should have been set to `False`
```

I tried to look for the error and I reached the previous issue. How is this related? How can I fix it most importantly? Many thanks!

**Comment by awaelchli** [comment] 2023-11-05 22:27
I don't know how to fix it sorry, I've never seen this occur on models we have worked with. Due to bandwidth limitations, I will only be able to work on it if it can be reproduced, apologies.

**Comment by asuglia-alana** [comment] 2023-11-06 09:04
Hello @awaelchli, I totally understand. I have tried to reproduce it in the following snippet:

```
import torch
import lightning as L
from lightning.fabric.strategies.fsdp import FSDPStrategy

class BoringModel(torch.nn.Module):
  def __init__(self):
    super().__init__()
    self.model = torch.nn.Sequential(
      torch.nn.Linear(5, 5), 
      torch.nn.ReLU(), 
      torch.nn.Linear(5, 1))
    self.pretrained_model = torch.nn.Sequential(
      torch.nn.Linear(5, 5),
      torch.nn.ReLU(), 
    )

  def forward(self, x1, x2):
    x2_hidden = self.pretrained_model(x2)

    hiddens = torch.cat([x1, x2_hidden], dim=1)

    return self.model(hiddens)

def setup():
  strategy = FSDPStrategy(
            auto_wrap_policy={torch.nn.Linear},
            activation_checkpointing_policy={torch.nn.Linear},
            state_dict_type="full",
            limit_all_gathers=True,
            cpu_offload=False,
        )
  fabric = L.Fabric(devices=2, accelerator="cuda", strategy=strategy)
  fabric.launch(main)

def main(fabric: L.Fabric):
  with fabric.init_module(empty_init=True):
      model = BoringModel()

  model = fabric.setup_module(model)
  # BUG: if you comment this line, script will work! 
  fabric.save("model.ckpt", {"pretrained":model.pretrained_model})
  fabric.print(model)

  batch_size = 2
  seqlen = 6
  embsize = 5
  with fabric.no_backward_sync(model, enabled=True):
    x1 = torch.ones((batch_size, seqlen, embsize))
    x2 = torch.ones((batch_size, seqlen, embsize)) * 2

    y = model(x1, x2)

if __name__ == "__main__":

  setup()
```

So seems to me that saving a checkpoint before starting the forward generates the error. When completing a `load_raw` before the forward also generates the same issue. Does this help?

**Comment by awaelchli** [comment] 2023-11-06 12:32
Thanks @asuglia-alana, this is very valuable. With this I can reduce it to a raw PyTorch FSDP example and report an issue over at PyTorch if there is one to be discovered. 

But I see now how you are saving the model. The thing to know here is that the way you save it now, it won't be easily possible to load it back! We actually have a different API for saving a partial model like you do, using the filter argument described here in the "Save a partial checkpoint" section of the docs: https://lightning.ai/docs/fabric/stable/guide/checkpoint.html#save-a-partial-checkpoint

Applied to your code snippet above, I can successfully avoid the error you are seeing with this modification:

```py
filter = {"pretrained": lambda k, v: k.startswith("pretrained")}
fabric.save("model.ckpt", {"pretrained": model}, filter=filter)
```
And we can also verify that it can be loaded back using:

```py
fabric.load("model.ckpt", {"pretrained": model}, strict=False)
```


I hope this helps to unblock you.

**Comment by awaelchli** [comment] 2023-11-10 23:18
I extracted a raw PyTorch example and submitted a ticket: https://github.com/pytorch/pytorch/issues/113496

**Comment by awaelchli** [comment] 2024-01-31 03:18
Closing this ticket for now since the problem needs to be fixed in PyTorch.

**Closed by awaelchli** 2024-01-31 03:18 UTC
Labels: question, 3rd party, strategy: fsdp, ver: 2.1.x
