### ISSUE TITLE
Converting deepspeed checkpoint to fp32

### ISSUE THREAD

**Issue by kushalj001** [Lightning-AI/pytorch-lightning#17425] opened 2023-04-21 07:06 UTC
### Bug description

Hi,
I finetuned a flan-t5-xl on 6 A100 GPUs using deepspeed stage 2. The checkpoint folder has two files related to optim states and model states,
![image](https://user-images.githubusercontent.com/32245327/233563779-793ccbb5-935b-4991-a784-3d7051c6b7a1.png)
When I try to use the conversion function given in the docs to convert this checkpoint to fp32 ([Train 1 trillion+ parameter models — PyTorch Lightning 2.0.1.post0 documentation](https://lightning.ai/docs/pytorch/stable/advanced/model_parallel.html#collating-single-file-checkpoint-for-deepspeed-zero-stage-3)), I get the following error,

```
2023-04-19 11:26:14.947199: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic$collating deepspeed ckpt to single file...
Processing zero checkpoint './checkpoints/google/flan-t5-xl-a100_80gb-ds2-bs2/epoch=03-val_loss=0.00.ckpt/checkpoint'
Detected checkpoint of type zero stage 2, world_size: 1
Parsing checkpoint created by deepspeed==0.8.3
Reconstructed fp32 state dict with 558 params 2849757184 elements
Traceback (most recent call last):
  File "test.py", line 11, in <module>
    convert_zero_checkpoint_to_fp32_state_dict(save_path, output_path)
  File "/cluster/home/kujain/.local/lib/python3.8/site-packages/lightning/pytorch/utilities/deepspeed.py", line 96, in $    optim_state = torch.load(optim_files[0], map_location=CPU_DEVICE)
  File "/cluster/home/kujain/.local/lib/python3.8/site-packages/torch/serialization.py", line 789, in load
    return _load(opened_zipfile, map_location, pickle_module, **pickle_load_args)
  File "/cluster/home/kujain/.local/lib/python3.8/site-packages/torch/serialization.py", line 1131, in _load
    result = unpickler.load()
  File "/cluster/apps/nss/gcc-6.3.0/python/3.8.5/x86_64/lib64/python3.8/pickle.py", line 1210, in load
    dispatch[key[0]](self)
  File "/cluster/apps/nss/gcc-6.3.0/python/3.8.5/x86_64/lib64/python3.8/pickle.py", line 1251, in load_binpersid
    self.append(self.persistent_load(pid))
  File "/cluster/home/kujain/.local/lib/python3.8/site-packages/torch/serialization.py", line 1101, in persistent_load
    load_tensor(dtype, nbytes, key, _maybe_decode_ascii(location))
  File "/cluster/home/kujain/.local/lib/python3.8/site-packages/torch/serialization.py", line 1079, in load_tensor
    storage = zip_file.get_storage_from_record(name, numel, torch.UntypedStorage).storage().untyped()
OSError: [Errno 14] Bad address)
```

I am not able to understand or debug this issue. Can anyone explain what’s going on here?
Also, do the checkpoint files make sense above? Assuming I finetuned my model on 6 GPUs I was expecting more sharded files of either the model states or optim states but I only see the file with 00 rank. Is this understanding correct?

Thank you

### What version are you seeing the problem on?

2.0+

### How to reproduce the bug

```python
Model saved using:
ds_strategy = DeepSpeedStrategy(
        zero_optimization=True,
        stage=2,
        offload_optimizer=False,
        offload_parameters=False,
    )
    checkpoint_callback = ModelCheckpoint(
        dirpath=f"./checkpoints/{args.model_name}-{args.gpu_name}-ds{args.ds_stage}-bs{args.batch_size}",
        filename="{epoch:02d}-{val_loss:.2f}",
        monitor="val_loss",
        save_top_k=-1,
        every_n_epochs=1,
    )
    trainer = pl.Trainer(
        logger=wandb_logger, 
        max_epochs=num_epochs,
        precision="bf16-mixed",
        accelerator="gpu",
        num_nodes=1, # must match the slurm --nodes
        devices=-1, # must match slurm --ntasks-per-node
        strategy=ds_strategy,
        callbacks=[checkpoint_callback]
    )

Conversion:
print("collating deepspeed ckpt to single file...")
save_path = "./checkpoints/google/flan-t5-xl-a100_80gb-ds2-bs2/epoch=03-val_loss=0.00.ckpt"
output_path = "./flan_full_model_ds2_bs2.pt"
convert_zero_checkpoint_to_fp32_state_dict(save_path, output_path)
```

### Environment

<details>
  <summary>Current environment</summary>

```
#- Lightning Component (e.g. Trainer, LightningModule, LightningApp, LightningWork, LightningFlow): Trainer, LighningModule
#- PyTorch Lightning Version (e.g., 2.0.0):
#- Lightning App Version (e.g., 0.5.2):
#- PyTorch Version (e.g., 1.13.1):
#- Python version (e.g., 3.8.5):
#- OS (e.g., Linux):
#- CUDA/cuDNN version: 11.7.0/8.4.0.27
#- GPU models and configuration: 6 A100 80GB
#- How you installed Lightning(`conda`, `pip`, source): pip
#- Running environment of LightningApp (e.g. local, cloud): 
```

</details>

cc @awaelchli

**Comment by awaelchli** [comment] 2023-07-19 13:08
Hi @kushalj001 
If you trained on 6 GPUs like you say, you should see 6 optimizer state files. Did you make sure to download all files from the server?

**Comment by awaelchli** [comment] 2023-12-29 17:01
Closing, since it looks unrelated to lightning without further information how to reproduce. There are clearly files missing from the downloaded folder. I hope you were able to resolve the issue in the mean time.

**Closed by awaelchli** 2023-12-29 17:01 UTC
Labels: bug, strategy: deepspeed, ver: 2.0.x
