### ISSUE TITLE
dataset downloading. 

### ISSUE THREAD

**Issue by Esmail-ibraheem** [Lightning-AI/pytorch-lightning#20047] opened 2024-07-04 15:34 UTC
### Bug description

 i am trying to download a dataset, but...

here it says that the data was successfully downloaded : 
![image](https://github.com/Lightning-AI/pytorch-lightning/assets/113830751/b395ebaa-d3fe-4d36-9efc-515c035194f3)

but did not find anything in my workspace, why is that? 
here is the code: 
![image](https://github.com/Lightning-AI/pytorch-lightning/assets/113830751/1613d1a4-fdcb-4426-bf41-96f042fb57f6)

### What version are you seeing the problem on?

master

### Error messages and logs

```
# Error messages and logs here please
```

### Environment

<details>
  <summary>Current environment</summary>

```
#- Lightning Component (e.g. Trainer, LightningModule, LightningApp, LightningWork, LightningFlow):
#- PyTorch Lightning Version (e.g., 1.5.0):
#- Lightning App Version (e.g., 0.5.2):
#- PyTorch Version (e.g., 2.0):
#- Python version (e.g., 3.9):
#- OS (e.g., Linux):
#- CUDA/cuDNN version:
#- GPU models and configuration:
#- How you installed Lightning(`conda`, `pip`, source):
#- Running environment of LightningApp (e.g. local, cloud):
```

</details>

**Comment by awaelchli** [comment] 2024-07-04 15:53
Hey @Esmail-ibraheem 

This project, pytorch-lightning, is not the same as Lightning Studio. If you'd like to get help with it, I suggest to post your question in our Discord server in the future: https://discord.com/invite/tfXFetEZxv

But I can answer your question of course. You are downloading a dataset using the function from huggingface datasets, and this will save the files in a hidden cache folder in your home folder. That's why you don't see it and that's completely normal. This would be the same even on your laptop outside of Studios!

If you'd like to explicitly control where the data is stored, simply pass the cache folder explicitly with the path where you'd like to save:

```py
ds = load_dataset(..., cache_dir="./data")
```

I'll close the issue now because it's not a bug for pytorch-lightning, but I'll be happy to continue answer your questions here or on Discord.

**Closed by awaelchli** 2024-07-04 15:53 UTC
Labels: bug, needs triage, ver: 2.2.x

**Comment by Esmail-ibraheem** [comment] 2024-07-04 16:02
thank you @awaelchli
